### ISSUE TITLE
Where is autoload.php

### ISSUE THREAD

**Issue by peter279k** [ua1-labs/firetest#5]
As title, firstly looking at this [code](https://github.com/ua1-labs/firetest/blob/master/scripts/runner.php#L20).

It seems that there's not any PHP file named `autoload.php` on this project folder.

I guess this file is generated by `composer` after executing the `composer install`.

But the `autoload.php` file is placed on `vendor` folder.

This line is possible to change into `require_once __DIR__ . '/../../../vendor/autoload.php';`.

**Comment by joshualjohnson** [comment]
This script file is a runner for when you import this library into other PHP projects. Notice in this project, we are running this script as the FireTest runner. https://github.com/ua1-labs/firedi/blob/master/composer.json#L25. Its simpler to do that now, then for us to implement a command line. Though, that is something we are considering.

**Comment by peter279k** [comment]
Ok. It makes sense. Closed.
